[project]
name = "opendatastudio-cli"
version = "0.0.0"
description = ""
requires-python = ">=3.11"
authors = [
    { name = "Varvara Efremova", email = "varvara@echus.co" },
    { name = "James Wilmot", email = "jameswilmot2000@gmail.com" },
]
dependencies = [
    "typer >= 0.12, < 1",
    "docker >= 7, < 8",
    "GitPython >= 3.1, < 4",
]

[tool.setuptools]
# Required to avoid setuptools erroring out when using pip-compile
py-modules = []
